#Real Estate Price Prediction Project


# Importing the libraries

In [ ]:
import numpy as np
import pandas as pd # Data Manipulation, Data Cleaning, Data Exploration, Data Visualization
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn import linear_model
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

# Import the dataset

In [ ]:
df = pd.read_csv("/content/Housing.csv")

In [ ]:
df

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no   
1    12250000  8960         4          4        4      yes        no       no   
2    12250000  9960         3          2        2      yes        no      yes   
3    12215000  7500         4          2        2      yes        no      yes   
4    11410000  7420         4          1        2      yes       yes      yes   
..        ...   ...       ...        ...      ...      ...       ...      ...   
540   1820000  3000         2          1        1      yes        no      yes   
541   1767150  2400         3          1        1       no        no       no   
542   1750000  3620         2          1        1      yes        no       no   
543   1750000  2910         3          1        1       no        no       no   
544   1750000  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
0                no             yes        2      yes        furnished  
1                no             yes        3       no        furnished  
2                no              no        2      yes   semi-furnished  
3                no             yes        3      yes        furnished  
4                no             yes        2       no        furnished  
..              ...             ...      ...      ...              ...  
540              no              no        2       no      unfurnished  
541              no              no        0       no   semi-furnished  
542              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
544              no              no        0       no      unfurnished  

[545 rows x 13 columns]

In [ ]:
df.head(10)

price   area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  13300000   7420         4          2        3      yes        no       no   
1  12250000   8960         4          4        4      yes        no       no   
2  12250000   9960         3          2        2      yes        no      yes   
3  12215000   7500         4          2        2      yes        no      yes   
4  11410000   7420         4          1        2      yes       yes      yes   
5  10850000   7500         3          3        1      yes        no      yes   
6  10150000   8580         4          3        4      yes        no       no   
7  10150000  16200         5          3        2      yes        no       no   
8   9870000   8100         4          1        2      yes       yes      yes   
9   9800000   5750         3          2        4      yes       yes       no   

  hotwaterheating airconditioning  parking prefarea furnishingstatus  
0              no             yes        2      yes        furnished  
1              no             yes        3       no        furnished  
2              no              no        2      yes   semi-furnished  
3              no             yes        3      yes        furnished  
4              no             yes        2       no        furnished  
5              no             yes        2      yes   semi-furnished  
6              no             yes        2      yes   semi-furnished  
7              no              no        0       no      unfurnished  
8              no             yes        2      yes        furnished  
9              no             yes        1      yes      unfurnished

In [ ]:
df.tail(15)

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
530  2240000  1950         3          1        1       no        no       no   
531  2233000  5300         3          1        1       no        no       no   
532  2135000  3000         2          1        1       no        no       no   
533  2100000  2400         3          1        2      yes        no       no   
534  2100000  3000         4          1        2      yes        no       no   
535  2100000  3360         2          1        1      yes        no       no   
536  1960000  3420         5          1        2       no        no       no   
537  1890000  1700         3          1        2      yes        no       no   
538  1890000  3649         2          1        1      yes        no       no   
539  1855000  2990         2          1        1       no        no       no   
540  1820000  3000         2          1        1      yes        no      yes   
541  1767150  2400         3          1        1       no        no       no   
542  1750000  3620         2          1        1      yes        no       no   
543  1750000  2910         3          1        1       no        no       no   
544  1750000  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
530             yes              no        0       no      unfurnished  
531              no             yes        0      yes      unfurnished  
532              no              no        0       no      unfurnished  
533              no              no        0       no      unfurnished  
534              no              no        0       no      unfurnished  
535              no              no        1       no      unfurnished  
536              no              no        0       no      unfurnished  
537              no              no        0       no      unfurnished  
538              no              no        0       no      unfurnished  
539              no              no        1       no      unfurnished  
540              no              no        2       no      unfurnished  
541              no              no        0       no   semi-furnished  
542              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
544              no              no        0       no      unfurnished

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   price             545 non-null    int64 
 1   area              545 non-null    int64 
 2   bedrooms          545 non-null    int64 
 3   bathrooms         545 non-null    int64 
 4   stories           545 non-null    int64 
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64 
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB


#Processing the DATA

In [ ]:
d = {'no':0,'yes':1,'unfurnished':0,'semi-furnished':1,'furnished':2}
df = df.replace(d)

In [ ]:
df

price  area  bedrooms  bathrooms  stories  mainroad  guestroom  \
0    13300000  7420         4          2        3         1          0   
1    12250000  8960         4          4        4         1          0   
2    12250000  9960         3          2        2         1          0   
3    12215000  7500         4          2        2         1          0   
4    11410000  7420         4          1        2         1          1   
..        ...   ...       ...        ...      ...       ...        ...   
540   1820000  3000         2          1        1         1          0   
541   1767150  2400         3          1        1         0          0   
542   1750000  3620         2          1        1         1          0   
543   1750000  2910         3          1        1         0          0   
544   1750000  3850         3          1        2         1          0   

     basement  hotwaterheating  airconditioning  parking  prefarea  \
0           0                0                1        2         1   
1           0                0                1        3         0   
2           1                0                0        2         1   
3           1                0                1        3         1   
4           1                0                1        2         0   
..        ...              ...              ...      ...       ...   
540         1                0                0        2         0   
541         0                0                0        0         0   
542         0                0                0        0         0   
543         0                0                0        0         0   
544         0                0                0        0         0   

     furnishingstatus  
0                   2  
1                   2  
2                   1  
3                   2  
4                   2  
..                ...  
540                 0  
541                 1  
542                 0  
543                 2  
544                 0  

[545 rows x 13 columns]

In [ ]:
df.shape

(545, 13)

In [ ]:
df.describe()

price          area    bedrooms   bathrooms     stories  \
count  5.450000e+02    545.000000  545.000000  545.000000  545.000000   
mean   4.766729e+06   5150.541284    2.965138    1.286239    1.805505   
std    1.870440e+06   2170.141023    0.738064    0.502470    0.867492   
min    1.750000e+06   1650.000000    1.000000    1.000000    1.000000   
25%    3.430000e+06   3600.000000    2.000000    1.000000    1.000000   
50%    4.340000e+06   4600.000000    3.000000    1.000000    2.000000   
75%    5.740000e+06   6360.000000    3.000000    2.000000    2.000000   
max    1.330000e+07  16200.000000    6.000000    4.000000    4.000000   

         mainroad   guestroom    basement  hotwaterheating  airconditioning  \
count  545.000000  545.000000  545.000000       545.000000       545.000000   
mean     0.858716    0.177982    0.350459         0.045872         0.315596   
std      0.348635    0.382849    0.477552         0.209399         0.465180   
min      0.000000    0.000000    0.000000         0.000000         0.000000   
25%      1.000000    0.000000    0.000000         0.000000         0.000000   
50%      1.000000    0.000000    0.000000         0.000000         0.000000   
75%      1.000000    0.000000    1.000000         0.000000         1.000000   
max      1.000000    1.000000    1.000000         1.000000         1.000000   

          parking    prefarea  furnishingstatus  
count  545.000000  545.000000        545.000000  
mean     0.693578    0.234862          0.930275  
std      0.861586    0.424302          0.761373  
min      0.000000    0.000000          0.000000  
25%      0.000000    0.000000          0.000000  
50%      0.000000    0.000000          1.000000  
75%      1.000000    0.000000          2.000000  
max      3.000000    1.000000          2.000000

In [ ]:
df['price']

0      13300000
1      12250000
2      12250000
3      12215000
4      11410000
         ...   
540     1820000
541     1767150
542     1750000
543     1750000
544     1750000
Name: price, Length: 545, dtype: int64

In [ ]:
df.columns

Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus'],
      dtype='object')

In [ ]:
import math
median_area = math.floor(df.area.median())
median_area

df.area = df.area.fillna(median_area)

median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

df.bedrooms = df.bedrooms.fillna(median_bedrooms)

median_bathrooms = math.floor(df.bathrooms.median())
median_bathrooms

df.bathrooms = df.bathrooms.fillna(median_bathrooms)

median_stories = math.floor(df.stories.median())
median_stories

df.stories = df.stories.fillna(median_stories)

median_mainroad = math.floor(df.mainroad.median())
median_mainroad

df.mainroad = df.mainroad.fillna(median_mainroad)

median_guestroom = math.floor(df.guestroom.median())
median_guestroom

df.guestroom = df.guestroom.fillna(median_guestroom)

median_basement = math.floor(df.basement.median())
median_basement

df.basement = df.basement.fillna(median_basement)

median_hotwaterheating = math.floor(df.hotwaterheating.median())
median_hotwaterheating

df.hotwaterheating = df.hotwaterheating.fillna(median_hotwaterheating)

median_airconditioning = math.floor(df.airconditioning.median())
median_airconditioning

df.airconditioning = df.airconditioning.fillna(median_airconditioning)

median_parking = math.floor(df.parking.median())
median_parking

df.parking = df.parking.fillna(median_parking)

median_prefarea = math.floor(df.prefarea.median())
median_prefarea

df.prefarea = df.prefarea.fillna(median_prefarea)

median_furnishingstatus = math.floor(df.furnishingstatus.median())
median_furnishingstatus

df.furnishingstatus = df.furnishingstatus.fillna(median_furnishingstatus)

#Training the DATA

In [ ]:
reg = linear_model.LinearRegression()
reg.fit(df[['area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus']],df.price)

LinearRegression()

In [ ]:
reg.coef_

array([2.43906887e+02, 1.19474386e+05, 9.88888287e+05, 4.50391518e+05,
       4.23100741e+05, 2.98030507e+05, 3.57926360e+05, 8.72936027e+05,
       8.53633595e+05, 2.79785637e+05, 6.47055599e+05, 2.13187781e+05])

In [ ]:
reg.intercept_

-324509.0498633804

#Testing The DATA

In [ ]:
reg.predict([[8100,4,1,2,1,1,1,0,1,2,1,2]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([7584399.24465679])

In [ ]:
reg.predict([[9520,4,1,2,1,0,1,0,1,2,0,2]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([6985660.91907699])

In [ ]:
reg.predict([[4200,3,1,1,0,1,1,0,1,2,0,2]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([4993140.14035952])